### PR TITLE
Improve website performance using caches.

### PR DESCRIPTION
**Pull request by mike-roberts1**

### CODE REVIEW

**Review by rosscooperman — APPROVED** [review]
Looks good. Only concern is whether we're using caches to cover an architectural problem. In general I wouldn't think there would be enough traffic to cause performance problems.

**Comment by mike-roberts1** [comment]
Yeah still trying to find ways to improve the website performance- I believe the lack of caches is having a "cascading delays" effect where longer slow requests cause other requests to take even longer. I've been experimenting with the number of gunicorn workers- otherwise next logical step seems to be building a robust caching layer on top of redis or moving to a framework/language with better performance.

**Comment by CrazyPython** [comment]
did you look at google pagespeed?

**Comment by mike-roberts1** [comment]
Good suggestion- currently getting a pretty bad score from pagespeed. Fortunately this caching code brought avg req time from around 2s to about 600ms. Will apply pagespeed suggestions later.

**Comment by CrazyPython** [comment]
There are Apache and Nginx modules that automatically speed up your app by Google Pagespeed.

**Comment by CrazyPython** [comment]
@mike-roberts1 ^

**Comment by mike-roberts1** [comment]
ugh- we're actually using heroku, which makes it a bit more difficult to set that up- have been working on other stuff since the page loading times have been relatively low.

**Comment by CrazyPython** [comment]
@mike-roberts1 hmm, perhaps it'd be worth changing out from heroku?

**Comment by mike-roberts1** [comment]
Actually just recently switched to heroku and off of AWS ECS since it gave better deployment features and less manual ops work. Am fairly busy at the moment working on other features but opened a new issue so I don't forget about this one.

https://github.com/cheddartv/stockstream.live/issues/8

**Pull request merged**
